export enum ActionTypeEnum {
    SET_IMAGE_PATH = "SET_IMAGE_PATH",
    SET_IMAGE_PROPERTIES = "SET_IMAGE_PROPERTIES",
    CHANGE_CROP_COORDINATES = "CHANGE_CROP_COORDINATES",
    TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING",
    SET_ERRORS = "SET_ERRORS",
    SET_FOR_SHARE = "SET_FOR_SHARE",
    SET_FOR_EDIT = "SET_FOR_EDIT",
    CHANGE_CROP_OPTIONS = "CHANGE_CROP_OPTIONS"
}